export const AiQuestions = [
  {
    id: "q1",
    question: "What does AI stand for?",
    options: [
      "Artificial Intelligence",
      "Automated Interface",
      "Applied Informatics",
      "Adaptive Internet",
    ],
    correctAnswer: "Artificial Intelligence",
  },
  {
    id: "q2",
    question:
      "Which field studies how to create machines that can learn from data?",
    options: [
      "Quantum Computing",
      "Machine Learning",
      "Network Security",
      "UX Design",
    ],
    correctAnswer: "Machine Learning",
  },
  {
    id: "q3",
    question: "What is supervised learning?",
    options: [
      "Learning with labeled data",
      "Learning without labels",
      "Learning by trial and error",
      "Learning in real-time",
    ],
    correctAnswer: "Learning with labeled data",
  },
  {
    id: "q4",
    question: "Which algorithm is used for classification and regression?",
    options: ["Decision Trees", "K‑means Clustering", "Apriori", "FFT"],
    correctAnswer: "Decision Trees",
  },
  {
    id: "q5",
    question: "Which model is known for sequence modeling tasks?",
    options: ["CNN", "RNN", "KNN", "PCA"],
    correctAnswer: "RNN",
  },
  {
    id: "q6",
    question: "What is reinforcement learning?",
    options: [
      "Learning via rewards and punishments",
      "Learning with no data",
      "Learning by imitating humans",
      "Learning with unlabeled data",
    ],
    correctAnswer: "Learning via rewards and punishments",
  },
  {
    id: "q7",
    question: "Which technique reduces dimensions of data?",
    options: ["PCA", "SVM", "KNN", "Naive Bayes"],
    correctAnswer: "PCA",
  },
  {
    id: "q8",
    question: "What does NLP stand for?",
    options: [
      "Natural Language Processing",
      "Neural Learning Protocol",
      "Network Layer Processing",
      "Normalized Logic Program",
    ],
    correctAnswer: "Natural Language Processing",
  },
  {
    id: "q9",
    question: "Which model architecture is used for images?",
    options: ["CNN", "RNN", "Transformer", "LSTM"],
    correctAnswer: "CNN",
  },
  {
    id: "q10",
    question: "What is overfitting?",
    options: [
      "Model too closely fits training data",
      "Model generalizes well",
      "Model performs poorly on training set",
      "Model uses too many features",
    ],
    correctAnswer: "Model too closely fits training data",
  },
  {
    id: "q11",
    question: "What is a common evaluation metric for classification?",
    options: ["Accuracy", "MSE", "Perplexity", "BLEU"],
    correctAnswer: "Accuracy",
  },
  {
    id: "q12",
    question: "What is transfer learning?",
    options: [
      "Using pre-trained models to solve new problems",
      "Training from scratch",
      "Transferring data between domains",
      "Reinforcement training",
    ],
    correctAnswer: "Using pre-trained models to solve new problems",
  },
  {
    id: "q13",
    question: "What is unsupervised learning?",
    options: [
      "Learning with unlabeled data",
      "Learning with labels",
      "Learning with rewards",
      "Learning by transfer",
    ],
    correctAnswer: "Learning with unlabeled data",
  },
  {
    id: "q14",
    question: "Which algorithm groups similar data points?",
    options: ["K-means", "Decision Tree", "Logistic Regression", "Naive Bayes"],
    correctAnswer: "K-means",
  },
  {
    id: "q15",
    question: "What is a neural network?",
    options: [
      "A set of algorithms modeled after the human brain",
      "A network of robots",
      "A database design",
      "A type of compiler",
    ],
    correctAnswer: "A set of algorithms modeled after the human brain",
  },
  {
    id: "q16",
    question: "What is the role of activation functions in neural networks?",
    options: [
      "Introduce non-linearity",
      "Normalize data",
      "Initialize weights",
      "Prevent overfitting",
    ],
    correctAnswer: "Introduce non-linearity",
  },
  {
    id: "q17",
    question: "Which is a popular optimizer?",
    options: ["Adam", "C4.5", "Apriori", "PageRank"],
    correctAnswer: "Adam",
  },
  {
    id: "q18",
    question: "What is the Turing Test designed to evaluate?",
    options: [
      "A machine's ability to exhibit human-like intelligence",
      "Speed of computation",
      "Memory usage",
      "Robustness to attacks",
    ],
    correctAnswer: "A machine's ability to exhibit human-like intelligence",
  },
  {
    id: "q19",
    question: "What is generative AI primarily used for?",
    options: [
      "Creating new content",
      "Detecting anomalies",
      "Database indexing",
      "Performance testing",
    ],
    correctAnswer: "Creating new content",
  },
  {
    id: "q20",
    question: "Which of these is a challenge in AI?",
    options: [
      "Bias in data",
      "Abundant labeled data",
      "Unlimited compute",
      "Static environments",
    ],
    correctAnswer: "Bias in data",
  },
];

export const GenAiQuestions = [
  {
    id: "q1",
    question: "What does Gen AI stand for?",
    options: [
      "Generative AI",
      "Generalized AI",
      "Generated Algorithmic Intelligence",
      "Generic AI",
    ],
    correctAnswer: "Generative AI",
  },
  {
    id: "q2",
    question: "Which is a popular generative AI model?",
    options: ["GPT", "ResNet", "SVM", "KNN"],
    correctAnswer: "GPT",
  },
  {
    id: "q3",
    question: "What is a use-case for Gen AI?",
    options: [
      "Image synthesis",
      "Sorting algorithms",
      "Data compression",
      "Static website hosting",
    ],
    correctAnswer: "Image synthesis",
  },
  {
    id: "q4",
    question: "Which model is used for text generation?",
    options: ["Transformer", "Random Forest", "K-means", "AdaBoost"],
    correctAnswer: "Transformer",
  },
  {
    id: "q5",
    question:
      "What is the main training objective of a language model like GPT?",
    options: [
      "Predict next word",
      "Classify images",
      "Cluster users",
      "Recommend products",
    ],
    correctAnswer: "Predict next word",
  },
  {
    id: "q6",
    question: "What is fine-tuning in Gen AI?",
    options: [
      "Adapting pre-trained model to a specific task",
      "Training from scratch",
      "Deleting model weights",
      "Shuffling data",
    ],
    correctAnswer: "Adapting pre-trained model to a specific task",
  },
  {
    id: "q7",
    question: "Which tool is used for image generation?",
    options: ["DALL-E", "Word2Vec", "KNN", "SIFT"],
    correctAnswer: "DALL-E",
  },
  {
    id: "q8",
    question: "What is prompt engineering?",
    options: [
      "Designing prompts to get better results",
      "Encrypting prompts",
      "Deleting prompts",
      "Compressing prompts",
    ],
    correctAnswer: "Designing prompts to get better results",
  },
  {
    id: "q9",
    question: "Which challenge is common in Gen AI?",
    options: [
      "Hallucinations",
      "Underfitting",
      "Noisy sensors",
      "Hardware failure",
    ],
    correctAnswer: "Hallucinations",
  },
  {
    id: "q10",
    question: "What is multimodal Gen AI?",
    options: [
      "Models combining text, image, etc.",
      "Voice-only models",
      "Statistical models",
      "Image filters",
    ],
    correctAnswer: "Models combining text, image, etc.",
  },
  {
    id: "q11",
    question: "Which is a risk with Gen AI?",
    options: [
      "Deepfake creation",
      "Slow sorting",
      "Low battery",
      "Stack overflow",
    ],
    correctAnswer: "Deepfake creation",
  },
  {
    id: "q12",
    question: "Which evaluation metric is used for text Gen AI?",
    options: ["Perplexity", "MSE", "IoU", "Accuracy"],
    correctAnswer: "Perplexity",
  },
  {
    id: "q13",
    question: "What is zero‑shot learning?",
    options: [
      "Performing tasks without task‑specific training",
      "Learning with lots of labels",
      "Augmenting data",
      "Batch training",
    ],
    correctAnswer: "Performing tasks without task‑specific training",
  },
  {
    id: "q14",
    question: "What is GPT‑4 an example of?",
    options: [
      "Large language model",
      "Decision tree",
      "Clustering algorithm",
      "Statistical test",
    ],
    correctAnswer: "Large language model",
  },
  {
    id: "q15",
    question: "Which architecture enables attention mechanisms?",
    options: ["Transformer", "Naive Bayes", "SVM", "RBF Network"],
    correctAnswer: "Transformer",
  },
  {
    id: "q16",
    question: "What is tokenization in NLP?",
    options: [
      "Splitting text into units",
      "Encrypting text",
      "Sorting text",
      "Translating text",
    ],
    correctAnswer: "Splitting text into units",
  },
  {
    id: "q17",
    question: "What is model inference?",
    options: [
      "Model making predictions",
      "Training the model",
      "Deleting the model",
      "Compressing the model",
    ],
    correctAnswer: "Model making predictions",
  },
  {
    id: "q18",
    question: "Which is an open-source Gen AI model?",
    options: ["Llama", "Excel", "Photoshop", "TensorFlow"],
    correctAnswer: "Llama",
  },
  {
    id: "q19",
    question: "Which company released ChatGPT?",
    options: ["OpenAI", "Google", "IBM", "Microsoft"],
    correctAnswer: "OpenAI",
  },
  {
    id: "q20",
    question: "What is an ethical concern in Gen AI?",
    options: [
      "Copyright infringement",
      "Project scheduling",
      "Cache invalidation",
      "Screen resolution",
    ],
    correctAnswer: "Copyright infringement",
  },
];

export const AgenticAIQuestions = [
  {
    id: "q1",
    question: "What is Agentic AI primarily about?",
    options: [
      "Autonomous agents acting without oversight",
      "Manual coding",
      "Database indexing",
      "Static analysis",
    ],
    correctAnswer: "Autonomous agents acting without oversight",
  },
  {
    id: "q2",
    question: "Which term describes agents that set their own goals?",
    options: ["Self‑agentic", "Reactive", "Supervised", "Scripted"],
    correctAnswer: "Self‑agentic",
  },
  {
    id: "q3",
    question: "What is a multi‑agent system?",
    options: [
      "Multiple AI agents interacting",
      "Single-agent firewall",
      "Database clusters",
      "Web services",
    ],
    correctAnswer: "Multiple AI agents interacting",
  },
  {
    id: "q4",
    question: "Which describes planning in Agentic AI?",
    options: [
      "Deciding sequence of actions",
      "Data labeling",
      "Sorting arrays",
      "Writing emails",
    ],
    correctAnswer: "Deciding sequence of actions",
  },
  {
    id: "q5",
    question: "What is reinforcement learning used for in agents?",
    options: [
      "Learning policies via reward",
      "Data encryption",
      "UI testing",
      "Network routing",
    ],
    correctAnswer: "Learning policies via reward",
  },
  {
    id: "q6",
    question: "What is emergence in multi‑agent environments?",
    options: [
      "Complex behavior from simple rules",
      "Debug logs",
      "API calls",
      "Cache hits",
    ],
    correctAnswer: "Complex behavior from simple rules",
  },
  {
    id: "q7",
    question: "Which is an example of an Agentic AI platform?",
    options: ["AutoGPT", "MySQL", "Photoshop", "iMovie"],
    correctAnswer: "AutoGPT",
  },
  {
    id: "q8",
    question: "What is tool‑use in Agentic AI?",
    options: [
      "Agents using external APIs",
      "Agents writing tools by hand",
      "Source control",
      "Testing frameworks",
    ],
    correctAnswer: "Agents using external APIs",
  },
  {
    id: "q9",
    question: "What is recursive reasoning?",
    options: [
      "Thinking about others thinking",
      "Nested loops",
      "Regex patterns",
      "Sorting data",
    ],
    correctAnswer: "Thinking about others thinking",
  },
  {
    id: "q10",
    question: "Which challenge arises in multi‑agent systems?",
    options: [
      "Coordination and conflict",
      "Display resolution",
      "Disk failure",
      "Network latency",
    ],
    correctAnswer: "Coordination and conflict",
  },
  {
    id: "q11",
    question: "What is delegation in agentic AI?",
    options: [
      "One agent delegating tasks to another",
      "Writing documentation",
      "Manual testing",
      "Email forwarding",
    ],
    correctAnswer: "One agent delegating tasks to another",
  },
  {
    id: "q12",
    question: "What is the role of memory in agents?",
    options: [
      "Store past experiences",
      "Store API keys",
      "Store logs",
      "Store configs",
    ],
    correctAnswer: "Store past experiences",
  },
  {
    id: "q13",
    question: "Which paradigm do agentic systems often use?",
    options: ["BDI – belief‑desire‑intention", "MVC", "MVC", "REST"],
    correctAnswer: "BDI – belief‑desire‑intention",
  },
  {
    id: "q14",
    question: "What does autonomy mean for agents?",
    options: [
      "Operate without human input",
      "Require manual trigger",
      "Only log data",
      "Shutdown immediately",
    ],
    correctAnswer: "Operate without human input",
  },
  {
    id: "q15",
    question: "What is an example domain for agents?",
    options: [
      "Automated trading",
      "Static site hosting",
      "Email drafting",
      "Graphic design",
    ],
    correctAnswer: "Automated trading",
  },
  {
    id: "q16",
    question: "What is a simulation environment for agents?",
    options: [
      "Sandbox world to test agents",
      "IDE plugin",
      "Database GUI",
      "Browser console",
    ],
    correctAnswer: "Sandbox world to test agents",
  },
  {
    id: "q17",
    question: "What is exploration vs exploitation balance?",
    options: [
      "Choosing new vs known strategies",
      "Memory vs CPU usage",
      "Network vs disk I/O",
      "API vs CLI",
    ],
    correctAnswer: "Choosing new vs known strategies",
  },
  {
    id: "q18",
    question: "What is chain‑of‑thought prompting?",
    options: [
      "Agents verbalizing reasoning steps",
      "Encrypting thoughts",
      "Joining chats",
      "Sorting logs",
    ],
    correctAnswer: "Agents verbalizing reasoning steps",
  },
  {
    id: "q19",
    question: "Which is a safety concern for agentic AI?",
    options: [
      "Unintended autonomous actions",
      "Slow loading UI",
      "Memory leaks",
      "Dependency hell",
    ],
    correctAnswer: "Unintended autonomous actions",
  },
  {
    id: "q20",
    question: "What is hierarchical planning?",
    options: [
      "High‑level and low‑level goal decomposition",
      "Single loop planning",
      "Flat file storage",
      "Network routing",
    ],
    correctAnswer: "High‑level and low‑level goal decomposition",
  },
];

export const BlockchainQuestions = [
  {
    id: "q1",
    question: "What is a blockchain?",
    options: [
      "Distributed ledger",
      "Central database",
      "Image format",
      "Encryption algorithm",
    ],
    correctAnswer: "Distributed ledger",
  },
  {
    id: "q2",
    question: "Which is the first blockchain?",
    options: ["Bitcoin", "Ethereum", "Litecoin", "Ripple"],
    correctAnswer: "Bitcoin",
  },
  {
    id: "q3",
    question: "What is a block?",
    options: [
      "Group of transactions",
      "Single transaction",
      "Encryption key",
      "Smart contract",
    ],
    correctAnswer: "Group of transactions",
  },
  {
    id: "q4",
    question: "What does mining do?",
    options: [
      "Validate transactions",
      "Design UI",
      "Host websites",
      "Compile code",
    ],
    correctAnswer: "Validate transactions",
  },
  {
    id: "q5",
    question: "What is a smart contract?",
    options: [
      "Self‑executing code on blockchain",
      "Manual contract",
      "PDF document",
      "Encryption protocol",
    ],
    correctAnswer: "Self‑executing code on blockchain",
  },
  {
    id: "q6",
    question: "Which consensus mechanism uses energy-intensive computation?",
    options: [
      "Proof of Work",
      "Proof of Stake",
      "Delegated PoS",
      "Byzantine Fault Tolerance",
    ],
    correctAnswer: "Proof of Work",
  },
  {
    id: "q7",
    question: "What is Proof of Stake?",
    options: [
      "Consensus via holding coins",
      "Proof of energy",
      "Mining with GPUs",
      "Central authority",
    ],
    correctAnswer: "Consensus via holding coins",
  },
  {
    id: "q8",
    question: "Which blockchain enables smart contracts?",
    options: ["Ethereum", "Bitcoin", "Monero", "Dogecoin"],
    correctAnswer: "Ethereum",
  },
  {
    id: "q9",
    question: "What is decentralization?",
    options: [
      "No single controlling entity",
      "One server controls everything",
      "Private cloud",
      "Data center",
    ],
    correctAnswer: "No single controlling entity",
  },
  {
    id: "q10",
    question: "What is a wallet in blockchain?",
    options: [
      "Key‑pair management tool",
      "Cold storage",
      "Hardware device only",
      "Mining rig",
    ],
    correctAnswer: "Key‑pair management tool",
  },
  {
    id: "q11",
    question: "What is a transaction fee?",
    options: [
      "Spending on miners/validators",
      "Marketing fee",
      "Loan interest",
      "Cloud cost",
    ],
    correctAnswer: "Spending on miners/validators",
  },
  {
    id: "q12",
    question: "What is a node?",
    options: [
      "Participant in the network",
      "Smart contract",
      "Consensus method",
      "Token",
    ],
    correctAnswer: "Participant in the network",
  },
  {
    id: "q13",
    question: "Which is a layer‑2 solution?",
    options: ["Lightning Network", "Bitcoin Core", "Geth", "Metamask"],
    correctAnswer: "Lightning Network",
  },
  {
    id: "q14",
    question: "What is gas in Ethereum?",
    options: [
      "Fee to execute transactions",
      "Block reward",
      "Encryption protocol",
      "Wallet type",
    ],
    correctAnswer: "Fee to execute transactions",
  },
  {
    id: "q15",
    question: "What is a decentralized app (dApp)?",
    options: [
      "App on blockchain",
      "Native mobile app",
      "Web server",
      "Desktop software",
    ],
    correctAnswer: "App on blockchain",
  },
  {
    id: "q16",
    question: "What provides immutability in blockchain?",
    options: [
      "Cryptographic hashing",
      "Relational DB",
      "Flat files",
      "Web logs",
    ],
    correctAnswer: "Cryptographic hashing",
  },
  {
    id: "q17",
    question: "What is a 51% attack?",
    options: [
      "Majority control of mining power",
      "Identity theft",
      "Spam attack",
      "DDoS",
    ],
    correctAnswer: "Majority control of mining power",
  },
  {
    id: "q18",
    question: "What is tokenization?",
    options: [
      "Representing real assets as tokens",
      "Encrypting data",
      "Two-factor auth",
      "Digital signature",
    ],
    correctAnswer: "Representing real assets as tokens",
  },
  {
    id: "q19",
    question: "What is consensus?",
    options: [
      "Agreement among nodes on state",
      "Voting for databases",
      "UI design",
      "Sorting algorithm",
    ],
    correctAnswer: "Agreement among nodes on state",
  },
  {
    id: "q20",
    question: "Which term refers to splitting a blockchain’s workload?",
    options: ["Sharding", "Forking", "Merging", "Stacking"],
    correctAnswer: "Sharding",
  },
];

export const CybersecurityQuestions = [
  {
    id: "q1",
    question: "What is cybersecurity about?",
    options: [
      "Protecting systems and data",
      "Designing UI",
      "Building databases",
      "Writing content",
    ],
    correctAnswer: "Protecting systems and data",
  },
  {
    id: "q2",
    question: "What is a firewall?",
    options: [
      "Network security barrier",
      "Database engine",
      "Web server",
      "Programming language",
    ],
    correctAnswer: "Network security barrier",
  },
  {
    id: "q3",
    question: "What is phishing?",
    options: [
      "Email scam to steal info",
      "Sorting emails",
      "Encrypting data",
      "Performance testing",
    ],
    correctAnswer: "Email scam to steal info",
  },
  {
    id: "q4",
    question: "What does VPN do?",
    options: [
      "Encrypts network traffic",
      "Blocks malware",
      "Caches content",
      "Indexes files",
    ],
    correctAnswer: "Encrypts network traffic",
  },
  {
    id: "q5",
    question: "What is two‑factor authentication?",
    options: [
      "Two-step identity verification",
      "Two passwords",
      "Two emails",
      "Two IP addresses",
    ],
    correctAnswer: "Two-step identity verification",
  },
  {
    id: "q6",
    question: "What is malware?",
    options: [
      "Malicious software",
      "Backup tool",
      "Encryption algorithm",
      "Database",
    ],
    correctAnswer: "Malicious software",
  },
  {
    id: "q7",
    question: "What is a vulnerability?",
    options: [
      "Weakness attackers exploit",
      "Feature enhancement",
      "Database schema",
      "API endpoint",
    ],
    correctAnswer: "Weakness attackers exploit",
  },
  {
    id: "q8",
    question: "What is encryption?",
    options: [
      "Encoding data",
      "Deleting data",
      "Splitting data",
      "Backing up data",
    ],
    correctAnswer: "Encoding data",
  },
  {
    id: "q9",
    question: "What is a DDoS attack?",
    options: [
      "Overwhelming service with traffic",
      "Brute-force login",
      "Network sniffing",
      "File corruption",
    ],
    correctAnswer: "Overwhelming service with traffic",
  },
  {
    id: "q10",
    question: "What is a zero‑day?",
    options: [
      "Unknown vulnerability before patch",
      "Day with no attacks",
      "Backup file",
      "Network protocol",
    ],
    correctAnswer: "Unknown vulnerability before patch",
  },
  {
    id: "q11",
    question: "What is social engineering?",
    options: [
      "Manipulating people to break security",
      "Design mockups",
      "Data mining",
      "Log parsing",
    ],
    correctAnswer: "Manipulating people to break security",
  },
  {
    id: "q12",
    question: "What is a man‑in‑the‑middle attack?",
    options: [
      "Eavesdropping between parties",
      "UI intercept",
      "Code injection",
      "Malware upload",
    ],
    correctAnswer: "Eavesdropping between parties",
  },
  {
    id: "q13",
    question: "What does SSL/TLS do?",
    options: [
      "Encrypts data in transit",
      "Stores logs",
      "Manages memory",
      "Schedules tasks",
    ],
    correctAnswer: "Encrypts data in transit",
  },
  {
    id: "q14",
    question: "What is a honeypot?",
    options: [
      "Decoy system to trap attackers",
      "Database index",
      "Firewall rule",
      "User account",
    ],
    correctAnswer: "Decoy system to trap attackers",
  },
  {
    id: "q15",
    question: "What is endpoint security?",
    options: [
      "Protect devices that connect to a network",
      "Secure cloud apps",
      "Design web forms",
      "Monitor performance",
    ],
    correctAnswer: "Protect devices that connect to a network",
  },
  {
    id: "q16",
    question: "What is penetration testing?",
    options: [
      "Ethical hacking to find vulnerabilities",
      "Virus scanning",
      "Data backup",
      "Traffic shaping",
    ],
    correctAnswer: "Ethical hacking to find vulnerabilities",
  },
  {
    id: "q17",
    question: "What’s a strong password practice?",
    options: [
      "Use a password manager",
      "Write it on paper",
      "Reuse it everywhere",
      "Keep username same",
    ],
    correctAnswer: "Use a password manager",
  },
  {
    id: "q18",
    question: "What is multi‑factor authentication?",
    options: [
      "Multiple independent credential types",
      "Two phones",
      "Two websites",
      "Two emails",
    ],
    correctAnswer: "Multiple independent credential types",
  },
  {
    id: "q19",
    question: "What is patch management?",
    options: [
      "Updating software to fix vulnerabilities",
      "Deleting old files",
      "Indexing databases",
      "Designing UI",
    ],
    correctAnswer: "Updating software to fix vulnerabilities",
  },
  {
    id: "q20",
    question: "What does CIA triad stand for?",
    options: [
      "Confidentiality, Integrity, Availability",
      "Control, Isolation, Authentication",
      "Cache, Indexing, Analytics",
      "Connection, Internet, Access",
    ],
    correctAnswer: "Confidentiality, Integrity, Availability",
  },
];

export const CloudComputingQuestions = [
  {
    id: "q1",
    question: "What is cloud computing?",
    options: [
      "On-demand computing resources",
      "Local desktop apps",
      "Printed documents",
      "Mobile apps",
    ],
    correctAnswer: "On-demand computing resources",
  },
  {
    id: "q2",
    question: "Which is a cloud provider?",
    options: ["AWS", "Dell", "Intel", "Samsung"],
    correctAnswer: "AWS",
  },
  {
    id: "q3",
    question: "What does IaaS stand for?",
    options: [
      "Infrastructure as a Service",
      "Internet as a Service",
      "Integration as a Service",
      "Identity as a Service",
    ],
    correctAnswer: "Infrastructure as a Service",
  },
  {
    id: "q4",
    question: "What is PaaS?",
    options: [
      "Platform as a Service",
      "People as a Service",
      "Product as a Service",
      "Protocol as a Service",
    ],
    correctAnswer: "Platform as a Service",
  },
  {
    id: "q5",
    question: "What is SaaS?",
    options: [
      "Software as a Service",
      "Security as a Service",
      "Storage as a Service",
      "Server as a Service",
    ],
    correctAnswer: "Software as a Service",
  },
  {
    id: "q6",
    question: "What is serverless computing?",
    options: [
      "Managed functions with no server infrastructure to manage",
      "No servers anywhere",
      "Servers in home",
      "Local testing",
    ],
    correctAnswer: "Managed functions with no server infrastructure to manage",
  },
  {
    id: "q7",
    question: "What is autoscaling?",
    options: [
      "Automatic adjustment of compute resources",
      "Manual scaling",
      "Deleting servers",
      "UI resizing",
    ],
    correctAnswer: "Automatic adjustment of compute resources",
  },
  {
    id: "q8",
    question: "What is virtualization?",
    options: [
      "Running multiple virtual machines on one host",
      "Encrypting data",
      "Managing network",
      "Building mobile apps",
    ],
    correctAnswer: "Running multiple virtual machines on one host",
  },
  {
    id: "q9",
    question: "What is a hybrid cloud?",
    options: [
      "Combination of public and private clouds",
      "Only on-premise",
      "Only public",
      "Only private",
    ],
    correctAnswer: "Combination of public and private clouds",
  },
  {
    id: "q10",
    question: "What is a virtual private cloud (VPC)?",
    options: [
      "Isolated network in the cloud",
      "Physical cloud hardware",
      "Public website",
      "Email server",
    ],
    correctAnswer: "Isolated network in the cloud",
  },
  {
    id: "q11",
    question: "What is object storage?",
    options: [
      "Store files as objects with metadata",
      "Relational database",
      "Block storage",
      "Cache layer",
    ],
    correctAnswer: "Store files as objects with metadata",
  },
  {
    id: "q12",
    question: "What is CDN?",
    options: [
      "Content Delivery Network",
      "Cloud Data Node",
      "Cache Distribution Node",
      "Compute Delivery Network",
    ],
    correctAnswer: "Content Delivery Network",
  },
  {
    id: "q13",
    question: "What is microservices architecture?",
    options: [
      "Small, independent services",
      "Large monolithic apps",
      "Database schema",
      "Single-page app",
    ],
    correctAnswer: "Small, independent services",
  },
  {
    id: "q14",
    question: "What is containerization?",
    options: [
      "Packing code with dependencies in containers",
      "Encrypting containers",
      "Network routing",
      "CSS styling",
    ],
    correctAnswer: "Packing code with dependencies in containers",
  },
  {
    id: "q15",
    question: "Which tool is used for container orchestration?",
    options: ["Kubernetes", "Webpack", "Jenkins", "Terraform"],
    correctAnswer: "Kubernetes",
  },
  {
    id: "q16",
    question: "What is CI/CD?",
    options: [
      "Continuous Integration/Continuous Deployment",
      "Cloud Infrastructure/Cloud Development",
      "Code Inspection/Code Debugging",
      "Calendar Integration/Data Collection",
    ],
    correctAnswer: "Continuous Integration/Continuous Deployment",
  },
  {
    id: "q17",
    question: "What is edge computing?",
    options: [
      "Processing data near its source",
      "Central data center only",
      "Mobile app backend",
      "Cloud front-end",
    ],
    correctAnswer: "Processing data near its source",
  },
  {
    id: "q18",
    question: "What is load balancing?",
    options: [
      "Distributing traffic across servers",
      "Encrypting loads",
      "Queuing messages",
      "Building UI",
    ],
    correctAnswer: "Distributing traffic across servers",
  },
  {
    id: "q19",
    question: "What is multi-tenancy?",
    options: [
      "Serving multiple customers from shared resources",
      "Multiple servers per tenant",
      "Dedicated hardware only",
      "Single user systems",
    ],
    correctAnswer: "Serving multiple customers from shared resources",
  },
  {
    id: "q20",
    question: "Which is a serverless compute service?",
    options: ["AWS Lambda", "EC2", "S3", "RDS"],
    correctAnswer: "AWS Lambda",
  },
];
